version: '3.8'

services:
  uniguru-lm:
    build: .
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - QDRANT_HOST=qdrant
    depends_on:
      - mongo
      - qdrant
    volumes:
      - ./audio_cache:/app/audio_cache
      - ./logs:/app/logs
      # Mount NAS (adjust path as needed)
      - /mnt/nas/Guruukul_DB:/nas/Guruukul_DB
    networks:
      - uniguru-network

  mongo:
    image: mongo:5
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - uniguru-network

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - uniguru-network

  vaani-tts:
    # Replace with actual Vaani TTS image
    image: vaani-tts:latest
    ports:
      - "8081:8081"
    networks:
      - uniguru-network

networks:
  uniguru-network:
    driver: bridge

volumes:
  mongo_data:
  qdrant_data: