apiVersion: apps/v1
kind: Deployment
metadata:
  name: logistics-service
  namespace: bhiv-core
  labels:
    app: logistics-service
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: logistics-service
  template:
    metadata:
      labels:
        app: logistics-service
        version: v1
    spec:
      containers:
      - name: logistics
        image: bhiv/logistics-service:latest
        ports:
        - containerPort: 8001
        env:
        - name: SERVICE_NAME
          value: "logistics"
        - name: SERVICE_PORT
          value: "8001"
        - name: DATABASE_URL
          value: "postgresql://$(DATABASE_USER):$(DATABASE_PASSWORD)@$(DATABASE_HOST):$(DATABASE_PORT)/$(DATABASE_NAME)"
        - name: REDIS_URL
          value: "redis://$(REDIS_HOST):$(REDIS_PORT)"
        envFrom:
        - configMapRef:
            name: bhiv-config
        - secretRef:
            name: bhiv-secrets
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: logistics-service
  namespace: bhiv-core
  labels:
    app: logistics-service
spec:
  selector:
    app: logistics-service
  ports:
  - port: 8001
    targetPort: 8001
    name: http
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: logistics-hpa
  namespace: bhiv-core
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: logistics-service
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
